### ISSUE TITLE
Situations Page

### ISSUE THREAD

**Issue by Joao4569** [Joao4569/RainbowWarriors#1]
EPIC: UX and Design

As a **user** I can **look at different situations that users have encountered** so that **I can look at advice offered about how best to deal with those situations**

**Acceptance Criteria**
- [ ] Situations page contains informations submitted by users on how to deal with different situations encountered.

**Tasks**
- [ ] Create url for situations page
- [ ] Create database to hold situations
- [ ] Create view
