### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by aelfrith92** [Joao4569/RainbowWarriors#14]
EPIC: Initial setup - authentication

As a user I can authenticate so that I can post comments and interact with the website. Authentication also allows me to post resources and stories I went through as part of the LGBTQ+ community.

**Acceptance Criteria**
- [ ] The allauth functionality is set up
- [ ] The allauth templates are designed and style
- [ ] The allauth functionalities prevent non-auth user from posting or editing comments

**Tasks**
- [ ] allauth set-up
- [ ] allauth templates, style, and general design
- [ ] 403 page for non-auth user
