### ISSUE TITLE
Community Page

### ISSUE THREAD

**Issue by Joao4569** [Joao4569/RainbowWarriors#3]
EPIC: UX and Design

As a **user** I can **see national events and comment on these, and am able to see other users comments on these** so that **I can keep in touch with what is going on in the national and local community**

**Acceptance Criteria**
- [ ] Community page shows national events with links to these. 
- [ ] Community page allows users to comment on past and future events.

**Tasks**
- [ ] Create url for community page
- [ ] Create database for community issues and events
- [ ] Create view
