### ISSUE TITLE
Resources Page

### ISSUE THREAD

**Issue by Joao4569** [Joao4569/RainbowWarriors#4]
EPIC: UX and Design

As a **user** I can **access resources that other users have added, resources to be focused on literature clips, movie clips, pictures of events that have taken place** so that **users can see relevant resources.**

**Acceptance Criteria**
- [x] Resources page is created, users can add relevant resources to it.

**Tasks**
- [x] Create url for resources page
- [x] Create view
- [x] Create resources data model
- [x] Create Category data model
- [x] Create Resources app
- [x] Add content to resourcess.html
- [x] Test resourcess.html template
- [x] Test User resources model
- [x] Test category model
- [x] Source images for page
- [x] Source resources for page
