### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Joao4569** [Joao4569/RainbowWarriors#5]
EPIC: UX and Design

As a **user** I can **see a logo for the site in the navbar** so that **when I click on the logo I know that I will be taken back to the home page.**

**Acceptance Criteria**
- [x] Logo is relevant to the theme of the site and clearly displayed in the top left corner of the navbar

**Tasks**
- [x] Create logo either original design or from free logo sites.
- [ ] Credits for designs to be put in readme.
