### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by Joao4569** [Joao4569/RainbowWarriors#6]
EPIC: UX and Design

As a **user** I can **see a favicon for the site in the navbar** so that **the favicon represents what the site is about.**

**Acceptance Criteria**
- [ ] Favicon is relevant to the theme of the site and clearly displayed in the title space/tab of the site at all times

**Tasks**
- [ ] Create favicon from free favicon creation site or create own. 
- [ ] Any credits for favicon to be put in readme.
